# Used Tabula to extract list of prison names and codes from Legal Aid Agency
# Guidance for Reporting Crime Lower Work PDF:
# https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/415165/reporting-crime-lower-work-guidance.pdf
#
# Extracted to: ./prison-codes.tsv
